import { useEffect, useMemo, useState } from 'react'
import {
  Activity, ArrowRight, Box, Check, CheckCircle2, ChevronDown, ChevronRight,
  CircleUserRound, Command, ExternalLink, FileCode2, GitBranch, GitPullRequest,
  LayoutGrid, Menu, Plus, Search, Settings, ShieldCheck, Sparkles, TerminalSquare,
  Users, X, Zap
} from 'lucide-react'

type View = 'overview' | 'catalog' | 'scorecards' | 'actions' | 'integrations'
type Service = { name:string; description:string; owner:string; system:string; lifecycle:string; language:string; score:number; repo:string; updated:string; initials:string; color:string }

const services: Service[] = [
  { name:'checkout-api', description:'Core checkout orchestration and payment routing.', owner:'Checkout', system:'Commerce', lifecycle:'Production', language:'TypeScript', score:94, repo:'northstar/checkout-api', updated:'8m ago', initials:'CA', color:'#6754e8' },
  { name:'customer-web', description:'Customer storefront and account experience.', owner:'Experience', system:'Commerce', lifecycle:'Production', language:'TypeScript', score:88, repo:'northstar/customer-web', updated:'23m ago', initials:'CW', color:'#137c8b' },
  { name:'identity-service', description:'Authentication, sessions, and access policies.', owner:'Foundations', system:'Identity', lifecycle:'Production', language:'Go', score:100, repo:'northstar/identity-service', updated:'1h ago', initials:'IS', color:'#d27328' },
  { name:'notification-worker', description:'Transactional email and event delivery.', owner:'Foundations', system:'Messaging', lifecycle:'Production', language:'Python', score:75, repo:'northstar/notification-worker', updated:'2h ago', initials:'NW', color:'#a64872' },
  { name:'recommendation-lab', description:'Experimental product ranking models.', owner:'Data', system:'Discovery', lifecycle:'Experimental', language:'Python', score:63, repo:'northstar/recommendation-lab', updated:'1d ago', initials:'RL', color:'#428654' },
]

const rules = [
  { title:'Service has an owner', detail:'spec.owner is present and resolves to a team', passing:5, total:5, level:'Required' },
  { title:'Lifecycle is declared', detail:'spec.lifecycle is one of production, experimental, or deprecated', passing:5, total:5, level:'Required' },
  { title:'Description is complete', detail:'metadata.description contains at least 20 characters', passing:4, total:5, level:'Recommended' },
  { title:'System is assigned', detail:'spec.system is present in the service metadata', passing:4, total:5, level:'Recommended' },
  { title:'Documentation link exists', detail:'spec.links contains a documentation entry', passing:3, total:5, level:'Recommended' },
]

function Logo(){ return <div className="logo"><div className="logo-mark"><span/><span/><span/></div><span>Northstar</span></div> }

function Sidebar({view,setView,open,setOpen}:{view:View,setView:(v:View)=>void,open:boolean,setOpen:(v:boolean)=>void}){
  const [user,setUser]=useState<{login:string;name:string;avatarUrl:string;role:string}|null>(null); const [githubReady,setGithubReady]=useState(false)
  useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(x=>setUser(x.user)).catch(()=>{});fetch('/api/github/status').then(r=>r.json()).then(x=>setGithubReady(x.configured)).catch(()=>{})},[])
  const links:[View,string,typeof LayoutGrid][] = [['overview','Overview',LayoutGrid],['catalog','Catalog',Box],['scorecards','Scorecards',ShieldCheck],['actions','Actions',Zap]]
  return <><aside className={open?'sidebar open':'sidebar'}>
    <div className="side-top"><Logo/><button className="mobile-close" onClick={()=>setOpen(false)}><X size={18}/></button></div>
    <nav>{links.map(([id,label,Icon])=><button key={id} className={view===id?'nav-link active':'nav-link'} onClick={()=>{setView(id);setOpen(false)}}><Icon size={18}/><span>{label}</span>{id==='catalog'&&<small>5</small>}</button>)}</nav>
    <div className="nav-group"><p>Manage</p><button className="nav-link"><Users size={18}/>Teams</button><button className={view==='integrations'?'nav-link active':'nav-link'} onClick={()=>{setView('integrations');setOpen(false)}}><GitBranch size={18}/>Integrations</button></div>
    <div className="side-bottom"><div className="sync-state"><span className={githubReady?'pulse':'pulse offline'}/><div><strong>{githubReady?'GitHub configured':'GitHub setup required'}</strong><small>{githubReady?'Ready to synchronize':'Open integrations to connect'}</small></div></div>{user?<button className="profile"><div className="avatar">{user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{user.name}</strong><small>{user.role==='admin'?'Administrator':'Member'}</small></div><ChevronDown size={16}/></button>:<button className="profile sign-in" onClick={()=>location.assign('/api/auth/login')}><div className="avatar"><CircleUserRound size={16}/></div><div><strong>Sign in with GitHub</strong><small>Use your organization account</small></div><ArrowRight size={15}/></button>}</div>
  </aside>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</>
}

function Header({title,onMenu}:{title:string,onMenu:()=>void}){
  const [search,setSearch]=useState(false)
  return <header><div className="header-title"><button className="menu" onClick={onMenu}><Menu size={20}/></button><span className="crumb">Northstar</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="header-actions">
    <button className={search?'search active':'search'} onClick={()=>setSearch(true)}><Search size={17}/>{search?<input autoFocus placeholder="Search catalog…" onBlur={()=>setSearch(false)}/>:<><span>Search</span><kbd>⌘ K</kbd></>}</button>
    <button className="icon-btn" aria-label="Settings"><Settings size={18}/></button><button className="primary small"><Plus size={16}/>Create</button>
  </div></header>
}

function ScoreRing({score,small=false}:{score:number,small?:boolean}){return <div className={small?'score-ring small':'score-ring'} style={{'--score':`${score*3.6}deg`} as React.CSSProperties}><div><strong>{score}</strong>{!small&&<span>/100</span>}</div></div>}

function Overview({navigate}:{navigate:(v:View)=>void}){
  return <div className="page overview">
    <section className="welcome"><div><p className="eyebrow">Friday, 10 July</p><h1>Good afternoon, Alex.</h1><p>Your software estate is in good shape. Two services need attention.</p></div><button className="ghost-button" onClick={()=>navigate('catalog')}><Command size={16}/>Browse catalog</button></section>
    <section className="topology-card">
      <div className="topology-copy"><span className="status-chip"><span/>Live catalog</span><h2>Everything your teams<br/>build, in one clear view.</h2><p>5 services across 4 systems, owned by 4 teams.</p><button onClick={()=>navigate('catalog')}>Explore your catalog <ArrowRight size={16}/></button></div>
      <div className="orbit" aria-label="Service topology visualization"><div className="orbit-ring ring-a"/><div className="orbit-ring ring-b"/><div className="core"><div className="logo-mark dark"><span/><span/><span/></div></div>
        {[['Checkout','node-a'],['Customer web','node-b'],['Identity','node-c'],['Notifications','node-d']].map(([n,c])=><div key={n} className={`orbit-node ${c}`}><span/><strong>{n}</strong><small>Healthy</small></div>)}
      </div>
    </section>
    <div className="section-heading"><div><p className="eyebrow">YOUR SERVICES</p><h2>Recently updated</h2></div><button className="text-button" onClick={()=>navigate('catalog')}>View all services <ArrowRight size={15}/></button></div>
    <div className="service-strip">{services.slice(0,3).map(s=><ServiceCard key={s.name} service={s}/>)}</div>
    <div className="dashboard-grid">
      <section className="panel health-panel"><div className="panel-head"><div><p className="eyebrow">STANDARDS</p><h3>Catalog health</h3></div><button className="icon-btn"><ExternalLink size={16}/></button></div><div className="health-body"><ScoreRing score={84}/><div className="health-copy"><strong>Healthy, with room to improve</strong><p>4 of 5 services meet your required metadata standards.</p><button className="text-button" onClick={()=>navigate('scorecards')}>Review standards <ArrowRight size={14}/></button></div></div><div className="progress-row"><span><i className="green"/>Passing <b>18</b></span><span><i className="amber"/>Needs attention <b>4</b></span><span><i className="gray"/>Not evaluated <b>2</b></span></div></section>
      <section className="panel activity-panel"><div className="panel-head"><div><p className="eyebrow">ACTIVITY</p><h3>Latest changes</h3></div><button className="text-button">View all</button></div>
        {[['GitPullRequest','checkout-api','Metadata updated by Maya Chen','8 minutes ago'],['Check','identity-service','Passed all standards','1 hour ago'],['Plus','recommendation-lab','Registered by Leo Martin','Yesterday']].map(([i,n,d,t])=><div className="activity-item" key={n}><div className="activity-icon">{i==='Check'?<Check size={15}/>:i==='Plus'?<Plus size={15}/>:<GitPullRequest size={15}/>}</div><div><strong>{n}</strong><p>{d}</p></div><time>{t}</time></div>)}
      </section>
    </div>
  </div>
}

function ServiceCard({service}:{service:Service}){return <article className="service-card"><div className="service-top"><div className="service-icon" style={{background:service.color}}>{service.initials}</div><ScoreRing score={service.score} small/></div><h3>{service.name}</h3><p>{service.description}</p><div className="tags"><span>{service.lifecycle}</span><span>{service.language}</span></div><div className="service-footer"><div className="team-avatar">{service.owner[0]}</div><span>{service.owner}</span><small>{service.updated}</small></div></article>}

function Catalog(){
  const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Service|null>(null); const [catalog,setCatalog]=useState(services); const [live,setLive]=useState(false)
  useEffect(()=>{fetch('/api/services').then(r=>r.ok?r.json():Promise.reject()).then(({services:rows})=>{if(rows.length){setCatalog(rows.map((s:Record<string,unknown>)=>({name:String(s.name),description:String(s.description),owner:String(s.owner),system:String(s.system),lifecycle:String(s.lifecycle).replace(/^./,c=>c.toUpperCase()),language:String(s.language),score:Number(s.score),repo:String(s.repository),updated:'Just synced',initials:String(s.name).split('-').map((p:string)=>p[0]).join('').slice(0,2).toUpperCase(),color:'#5546d8'})));setLive(true)}}).catch(()=>{})},[])
  const filtered=useMemo(()=>catalog.filter(s=>(s.name+s.owner+s.system).toLowerCase().includes(query.toLowerCase())),[query,catalog])
  return <div className="page"><div className="page-intro"><div><p className="eyebrow">SOFTWARE CATALOG</p><h1>Services</h1><p>Everything your organization builds and owns.</p></div><button className="primary"><Plus size={17}/>Register service</button></div>
    <div className="catalog-toolbar"><div className="input-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services, teams, or systems"/></div><button className="filter">All systems <ChevronDown size={15}/></button><button className="filter">All owners <ChevronDown size={15}/></button><div className="result-count"><i className={live?'dot green':'dot gray'}/>{live?'Live data':'Demo data'} · {filtered.length} services</div></div>
    <div className="catalog-table"><div className="table-head"><span>Service</span><span>Owner</span><span>System</span><span>Lifecycle</span><span>Score</span><span/></div>{filtered.map(s=><button className="table-row" key={s.name} onClick={()=>setSelected(s)}><span className="service-cell"><i style={{background:s.color}}>{s.initials}</i><span><strong>{s.name}</strong><small>{s.description}</small></span></span><span><b className="mini-avatar">{s.owner[0]}</b>{s.owner}</span><span>{s.system}</span><span><i className={s.lifecycle==='Production'?'dot green':'dot purple'}/>{s.lifecycle}</span><span><ScoreRing score={s.score} small/></span><ChevronRight size={16}/></button>)}</div>
    {selected&&<div className="drawer-wrap"><div className="drawer-scrim" onClick={()=>setSelected(null)}/><aside className="drawer"><button className="drawer-close" onClick={()=>setSelected(null)}><X size={19}/></button><div className="drawer-title"><div className="service-icon large" style={{background:selected.color}}>{selected.initials}</div><div><p className="eyebrow">SERVICE</p><h2>{selected.name}</h2></div></div><p className="drawer-desc">{selected.description}</p><div className="drawer-score"><ScoreRing score={selected.score}/><div><strong>Metadata score</strong><p>{selected.score>=90?'Meets all required standards.':'A few recommended fields need attention.'}</p></div></div><h4>About</h4><dl><div><dt>Owner</dt><dd>{selected.owner}</dd></div><div><dt>System</dt><dd>{selected.system}</dd></div><div><dt>Lifecycle</dt><dd>{selected.lifecycle}</dd></div><div><dt>Language</dt><dd>{selected.language}</dd></div></dl><h4>Links</h4><a className="repo-link"><GitBranch size={17}/><span><strong>{selected.repo}</strong><small>Source repository</small></span><ExternalLink size={15}/></a><h4>Metadata</h4><pre><code><span>apiVersion:</span> northstar.dev/v1{`\n`}<span>kind:</span> Service{`\n`}<span>metadata:</span>{`\n`}  name: {selected.name}{`\n`}<span>spec:</span>{`\n`}  owner: team:{selected.owner.toLowerCase()}{`\n`}  lifecycle: {selected.lifecycle.toLowerCase()}</code></pre></aside></div>}
  </div>
}

function Scorecards(){return <div className="page"><div className="page-intro"><div><p className="eyebrow">STANDARDS</p><h1>Scorecards</h1><p>Turn your engineering expectations into visible, actionable checks.</p></div><button className="primary"><Plus size={17}/>New scorecard</button></div>
  <section className="score-hero"><div><span className="status-chip"><ShieldCheck size={14}/>Active scorecard</span><h2>Service metadata</h2><p>Baseline catalog quality for every registered service.</p><div className="hero-meta"><span>5 checks</span><span>5 services</span><span>Evaluated 8m ago</span></div></div><ScoreRing score={84}/></section>
  <div className="score-layout"><section className="rules"><div className="rules-head"><h3>Checks</h3><span>24 evaluations</span></div>{rules.map((r,i)=><div className="rule" key={r.title}><div className={r.passing===r.total?'rule-state pass':'rule-state warn'}>{r.passing===r.total?<Check size={16}/>:<Activity size={16}/>}</div><div className="rule-main"><div><strong>{r.title}</strong><span>{r.level}</span></div><p>{r.detail}</p></div><div className="rule-result"><strong>{r.passing}/{r.total}</strong><small>passing</small></div><ChevronRight size={17}/></div>)}</section><aside className="standards-aside"><h3>Coverage</h3><p>How services perform against this scorecard.</p>{services.map(s=><div className="coverage" key={s.name}><span><i style={{background:s.color}}>{s.initials}</i>{s.name}</span><div><b style={{width:`${s.score}%`}}/><em>{s.score}%</em></div></div>)}</aside></div>
  </div>}

function Actions(){const [running,setRunning]=useState(false);const [formOpen,setFormOpen]=useState(false);const [serviceName,setServiceName]=useState('');const [owner,setOwner]=useState('');const [result,setResult]=useState('');async function run(){setRunning(true);setResult('');try{const r=await fetch('/api/actions/dispatch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({inputs:{serviceName,owner}})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Dispatch failed');setResult('Workflow dispatched. Follow its progress in GitHub Actions.')}catch(e){setResult((e as Error).message)}finally{setRunning(false)}}return <div className="page"><div className="page-intro"><div><p className="eyebrow">SELF-SERVICE</p><h1>Actions</h1><p>Approved paths for the jobs developers do every week.</p></div><button className="primary"><Plus size={17}/>New template</button></div>
  <div className="action-grid"><article className="action-feature"><div className="action-art"><TerminalSquare size={38}/><span>workflow_dispatch</span></div><div><span className="status-chip"><Sparkles size={14}/>Most used</span><h2>Create a service</h2><p>Start a production-ready service with ownership, metadata, CI, and repository settings already in place.</p><div className="action-details"><span><GitBranch size={15}/>GitHub Actions</span><span><FileCode2 size={15}/>2 inputs</span><span><ShieldCheck size={15}/>Approved</span></div><button className="primary" onClick={()=>setFormOpen(true)}>Run action <ArrowRight size={16}/></button></div></article>
    {[['Request a repository','Create a governed repository with team access and branch protection.','RR'],['Register an existing service','Add metadata to a repository and bring it into the catalog.','RS'],['Archive a service','Mark a service as deprecated and archive its repository safely.','AS']].map(([t,d,x])=><article className="action-card" key={t}><div className="action-monogram">{x}</div><div><h3>{t}</h3><p>{d}</p></div><button><ArrowRight size={17}/></button></article>)}</div>
  <section className="panel run-history"><div className="panel-head"><div><p className="eyebrow">RECENT RUNS</p><h3>Workflow activity</h3></div><button className="text-button">View in GitHub <ExternalLink size={14}/></button></div><div className="run-row"><CheckCircle2 size={18}/><div><strong>Create a service</strong><small>payments-reconciliation · Run by Maya Chen</small></div><span>Completed in 1m 42s</span><time>2 hours ago</time></div><div className="run-row"><CheckCircle2 size={18}/><div><strong>Register an existing service</strong><small>customer-web · Run by Alex Berg</small></div><span>Completed in 18s</span><time>Yesterday</time></div></section>
  {formOpen&&<div className="drawer-wrap"><div className="drawer-scrim" onClick={()=>setFormOpen(false)}/><aside className="drawer action-drawer"><button className="drawer-close" onClick={()=>setFormOpen(false)}><X size={19}/></button><p className="eyebrow">GITHUB WORKFLOW</p><h2>Create a service</h2><p className="drawer-desc">Northstar will validate these inputs and dispatch the approved workflow. Secrets stay in GitHub.</p><label>Service name<input value={serviceName} onChange={e=>setServiceName(e.target.value)} placeholder="payments-api"/></label><label>Owning team<input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="team:payments"/></label>{result&&<div className={result.startsWith('Workflow')?'action-result success':'action-result'}>{result}</div>}<button className="primary action-submit" disabled={!serviceName||!owner||running} onClick={run}>{running?<><span className="spinner"/>Dispatching workflow…</>:<>Dispatch workflow <ArrowRight size={16}/></>}</button></aside></div>}
  </div>}

function Integrations(){
  const [status,setStatus]=useState<{configured:boolean;appId:string|null}|null>(null); const [installationId,setInstallationId]=useState(''); const [syncing,setSyncing]=useState(false); const [message,setMessage]=useState('')
  useEffect(()=>{fetch('/api/github/status').then(r=>r.json()).then(setStatus).catch(()=>setStatus({configured:false,appId:null}))},[])
  async function sync(){setSyncing(true);setMessage('');try{const r=await fetch('/api/github/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installationId:Number(installationId)})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Sync failed');setMessage(`Synced ${data.registered} services. ${data.unregistered} repositories need metadata.`)}catch(e){setMessage((e as Error).message)}finally{setSyncing(false)}}
  return <div className="page"><div className="page-intro"><div><p className="eyebrow">CONNECTIONS</p><h1>Integrations</h1><p>Connect the systems that describe and operate your software.</p></div></div><section className="integration-card"><div className="github-mark"><GitBranch size={25}/></div><div className="integration-main"><div className="integration-title"><div><h2>GitHub</h2><p>Discover repositories, read service metadata, and dispatch approved workflows.</p></div><span className={status?.configured?'connection connected':'connection'}><i/>{status?.configured?'Configured':'Setup required'}</span></div>{!status?.configured?<div className="setup-box"><div><strong>Configure your GitHub App</strong><p>Add the App ID, private key, and webhook secret to the environment, then restart Northstar.</p></div><code>cp .env.example .env</code><a href="https://github.com/settings/apps/new" target="_blank" rel="noreferrer">Create GitHub App <ExternalLink size={14}/></a></div>:<div className="sync-box"><div><label htmlFor="installation">Installation ID</label><input id="installation" value={installationId} onChange={e=>setInstallationId(e.target.value)} placeholder="12345678" inputMode="numeric"/></div><button className="primary" disabled={!installationId||syncing} onClick={sync}>{syncing?<><span className="spinner"/>Syncing…</>:<><Activity size={16}/>Sync now</>}</button>{message&&<p className="sync-message">{message}</p>}</div>}<div className="permission-row"><span><Check size={14}/>Contents: read</span><span><Check size={14}/>Actions: write</span><span><Check size={14}/>Metadata: read</span></div></div></section><section className="integration-empty"><Plus size={20}/><div><strong>More providers, same catalog</strong><p>The integration boundary is ready for GitLab and Bitbucket adapters.</p></div></section></div>
}

export function App(){const [view,setView]=useState<View>('overview'); const [sideOpen,setSideOpen]=useState(false); const title={overview:'Overview',catalog:'Catalog',scorecards:'Scorecards',actions:'Actions',integrations:'Integrations'}[view]
  return <div className="app"><Sidebar view={view} setView={setView} open={sideOpen} setOpen={setSideOpen}/><main><Header title={title} onMenu={()=>setSideOpen(true)}/>{view==='overview'?<Overview navigate={setView}/>:view==='catalog'?<Catalog/>:view==='scorecards'?<Scorecards/>:view==='actions'?<Actions/>:<Integrations/>}</main></div>}
