import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Check, Circle, Database, ExternalLink, GitBranch, Radar, ShieldCheck, Sparkles, X } from 'lucide-react'

type State={checks:Record<string,boolean>;complete:boolean;stats:{users:number;services:number;syncs:number};webhookUrl:string;webhookUrlPublic:boolean;missingDeployment:string[]}
const gates=[
  {id:'foundation',title:'Secure the foundation',body:'Verify the deployment connections and canonical Git configuration revision.',keys:['database','githubApp','oauth','webhookSecret','configRepository','configRevision'],icon:Database},
  {id:'identity',title:'Open the control room',body:'Sign in as the bootstrap administrator and choose the GitHub App installation.',keys:['administrator','installation'],icon:ShieldCheck},
  {id:'catalog',title:'Acquire the first signal',body:'Synchronize GitHub and register at least one service from repository metadata.',keys:['firstSync','firstService'],icon:Radar},
  {id:'experience',title:'Publish the portal',body:'Enable a scorecard and publish the first self-service workflow.',keys:['scorecard','publishedAction'],icon:Sparkles}
]

export function OnboardingGate({user,onRefresh,onOpenSettings}:{user:any;onRefresh:()=>void;onOpenSettings:()=>void}){
  const [state,setState]=useState<State|null>(null),[open,setOpen]=useState(false),[installation,setInstallation]=useState(''),[working,setWorking]=useState(false),[message,setMessage]=useState(''),[documentationUrl,setDocumentationUrl]=useState('')
  async function load(){const[x,portal]=await Promise.all([fetch('/api/onboarding').then(r=>r.json()),fetch('/api/portal').then(r=>r.json())]);setState(x);setDocumentationUrl(portal?.general?.documentationUrl||'');if(user?.role==='admin'&&!x.complete&&!sessionStorage.getItem('northstar-onboarding-dismissed'))setOpen(true)}
  useEffect(()=>{load()},[user?.role])
  const active=useMemo(()=>state?Math.max(0,gates.findIndex(g=>!g.keys.every(k=>state.checks[k]))):0,[state])
  async function connect(){setWorking(true);setMessage('');try{const c=await fetch('/api/admin/config').then(r=>r.json());const value={...c.effective.catalog,installationId:Number(installation)};const saved=await fetch('/api/admin/config/catalog',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({value})});if(!saved.ok)throw new Error((await saved.json()).error);const sync=await fetch('/api/github/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installationId:Number(installation)})});const result=await sync.json();if(!sync.ok)throw new Error(result.error);setMessage(`Synchronized ${result.registered} services.`);await load();onRefresh()}catch(e){setMessage((e as Error).message)}finally{setWorking(false)}}
  if(!state||user?.role!=='admin'||state.complete)return null
  return <>{!open&&<button className="setup-launcher" onClick={()=>setOpen(true)}><Radar size={15}/><span>Finish portal setup</span><b>{Object.values(state.checks).filter(Boolean).length}/{Object.keys(state.checks).length}</b></button>}{open&&<div className="onboarding-wrap"><div className="onboarding-scrim"/><section className="onboarding"><button className="onboarding-close" aria-label="Close setup" onClick={()=>{sessionStorage.setItem('northstar-onboarding-dismissed','1');setOpen(false)}}><X size={18}/></button><header className="onboarding-head"><div className="flight-mark"><Radar size={24}/></div><div><p className="eyebrow">FIRST-RUN SETUP</p><h1>Bring Perongen online.</h1><p>Each step is verified against the running portal.</p></div></header><div className="flight-path">{gates.map((g,i)=>{const done=g.keys.every(k=>state.checks[k]);const Icon=g.icon;return <button className={`${done?'done':''} ${active===i?'active':''}`} key={g.id}><span>{done?<Check size={14}/>:<Icon size={14}/>}</span><small>Gate {i+1}</small><strong>{g.title}</strong></button>})}</div><div className="gate-detail"><div className="gate-copy"><p className="eyebrow">GATE {active+1}</p><h2>{gates[active].title}</h2><p>{gates[active].body}</p>{gates[active].keys.map(k=><div className="readiness-row" key={k}>{state.checks[k]?<Check size={15}/>:<Circle size={15}/>}<span>{k.replace(/([A-Z])/g,' $1')}</span><strong>{state.checks[k]?'Ready':'Needs attention'}</strong></div>)}</div><aside className="gate-action">{active===0&&<Foundation state={state} checkAgain={load}/>} {active===1&&<><h3>GitHub installation</h3><p>Paste the installation ID shown in your GitHub App installation URL.</p><input value={installation} onChange={e=>setInstallation(e.target.value)} inputMode="numeric" placeholder="145753228"/><button className="primary" disabled={!installation||working} onClick={connect}>{working?'Connecting…':'Save and synchronize'} <ArrowRight size={14}/></button></>}{active===2&&<><h3>Catalog metadata</h3><p>Add the configured service metadata file to at least one repository, then synchronize again.</p><input value={installation} onChange={e=>setInstallation(e.target.value)} inputMode="numeric" placeholder="Installation ID"/><button className="primary" disabled={!installation||working} onClick={connect}>Synchronize now</button></>}{active===3&&<><h3>Shape the experience</h3><p>Use the visual builders to review scorecards and publish a workflow action.</p><button className="primary" onClick={()=>{setOpen(false);onOpenSettings()}}>Open builders <ArrowRight size={14}/></button></>}{documentationUrl&&<a className="onboarding-doc-link" href={documentationUrl} target="_blank" rel="noopener noreferrer">Open setup documentation <ExternalLink size={12}/></a>}{message&&<div className="onboarding-message">{message}</div>}</aside></div></section></div>}</>}
function Foundation({state,checkAgain}:{state:State;checkAgain:()=>void}){return <><GitBranch size={28}/><h3>{state.missingDeployment.length===1?'One deployment setting is missing':'Deployment settings'}</h3>{state.missingDeployment.length?<><p>Add <code>{state.missingDeployment.join(', ')}</code> to Perongen’s deployment environment.</p>{state.missingDeployment.includes('GITHUB_WEBHOOK_SECRET')&&<p>Generate a strong secret and use the identical value for <code>GITHUB_WEBHOOK_SECRET</code> and the GitHub App’s webhook secret.</p>}</>:<p>Deployment settings are available. Restart Perongen if they were added after this process started.</p>}<div className="webhook-address"><small>GitHub App webhook URL</small><code>{state.webhookUrl}</code></div>{!state.webhookUrlPublic&&<p><strong>This localhost URL is not reachable by GitHub.</strong> For webhook testing, set <code>PUBLIC_URL</code> to a public HTTPS tunnel or deployment URL.</p>}<p>Subscribe the GitHub App to <strong>Push</strong> events, restart Perongen, then check again.</p><button className="ghost-button" onClick={checkAgain}>Check again</button></>}
